apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: datadog-demo
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: payment-service
