apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: datadog-demo
data:
  DB_HOST: "datadog-demo-postgres.c7ckk2qsyz0a.eu-central-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"
  DB_USER: "dbadmin"
  REDIS_HOST: "datadog-demo-redis.xub3gr.0001.euc1.cache.amazonaws.com"
  REDIS_PORT: "6379"
